# Generated by Django 2.2 on 2019-12-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemeVoiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pb', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
        migrations.AddField(
            model_name='problemevoiture',
            name='voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Voiture'),
        ),
    ]
