# Generated by Django 2.2 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20191213_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemevoiture',
            name='nom_pb',
            field=models.CharField(choices=[('Assurance expirée', 'PB1'), ('Permis expiré', 'PB2'), ('Excès de vitesse', 'PB3'), ('Visite technique mensuelle non effectuée', 'PB4'), ('Taxes non payées', 'PB5')], max_length=80),
        ),
    ]
